### ISSUE TITLE
api requires token now

### ISSUE THREAD

**Issue by berkant** [ahstro/spotify-cover-fetch#1]

**Comment by omarcr** [comment]
How can I use the package now?

**Comment by ahstro** [comment]
@omarcr Sorry, guess you can't :/ Not really coding right now, and never using this, so not likely to fix it anytime soon. Feel free to fork or submit a PR or something though :)

**Comment by omarcr** [comment]
Ok I have made my own version in python.

https://github.com/omarcr/collage-from-spotify-playlist-artwork

Do you mind redirecting here from your main webpage?

Cheers 
Omar
